//#region create machine
export const CREATE_MACHINE_REQUESTED = 'machines.CREATE_MACHINE_REQUESTED';
export const CREATE_MACHINE_SUCCEEDED = 'machines.CREATE_MACHINE_SUCCEEDED';
export const CREATE_MACHINE_FAILED = 'machines.CREATE_MACHINE_FAILED';
export const CREATE_MACHINE_RESET = 'machines.CREATE_MACHINE_RESET';
//#endregion

//#region create machine attribute
export const CREATE_MACHINE_ATTRIBUTE_REQUESTED =
  'machines.CREATE_MACHINE_ATTRIBUTE_REQUESTED';
export const CREATE_MACHINE_ATTRIBUTE_SUCCEEDED =
  'machines.CREATE_MACHINE_ATTRIBUTE_SUCCEEDED';
export const CREATE_MACHINE_ATTRIBUTE_FAILED =
  'machines.CREATE_MACHINE_ATTRIBUTE_FAILED';
export const CREATE_MACHINE_ATTRIBUTE_RESET =
  'machines.CREATE_MACHINE_ATTRIBUTE_RESET';
//#endregion

//#region Update machine attribute
export const UPDATE_MACHINE_ATTRIBUTE_REQUESTED =
  'machines.UPDATE_MACHINE_ATTRIBUTE_REQUESTED';
export const UPDATE_MACHINE_ATTRIBUTE_SUCCEEDED =
  'machines.UPDATE_MACHINE_ATTRIBUTE_SUCCEEDED';
export const UPDATE_MACHINE_ATTRIBUTE_FAILED =
  'machines.UPDATE_MACHINE_ATTRIBUTE_FAILED';
export const UPDATE_MACHINE_ATTRIBUTE_RESET =
  'machines.UPDATE_MACHINE_ATTRIBUTE_RESET';
//#endregion

//#region DELETE MACHINE
export const DELETE_MACHINE_REQUESTED = 'machines.DELETE_MACHINE_REQUESTED';
export const DELETE_MACHINE_SUCCEEDED = 'machines.DELETE_MACHINE_SUCCEEDED';
export const DELETE_MACHINE_FAILED = 'machines.DELETE_MACHINE_FAILED';
export const DELETE_MACHINE_RESET = 'machines.DELETE_MACHINE_RESET';
//#endregion

//#region Delete machine attributes
export const DELETE_MACHINE_ATTRIBUTE_REQUESTED =
  'machines.DELETE_MACHINE_ATTRIBUTE_REQUESTED';
export const DELETE_MACHINE_ATTRIBUTE_SUCCEEDED =
  'machines.DELETE_MACHINE_ATTRIBUTE_SUCCEEDED';
export const DELETE_MACHINE_ATTRIBUTE_FAILED =
  'machines.DELETE_MACHINE_ATTRIBUTE_FAILED';
export const DELETE_MACHINE_ATTRIBUTE_RESET =
  'machines.DELETE_MACHINE_ATTRIBUTE_RESET';
//#endregion
